# Generated by Django 3.2.18 on 2023-06-07 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_difficulty'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='fridge',
            field=models.ManyToManyField(blank=True, related_name='fridge_users', through='accounts.UserIngredient', to='recipes.Ingredient'),
        ),
    ]
