# Generated by Django 3.2.18 on 2023-06-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_views'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useringredient',
            name='viewed_recipes',
            field=models.ManyToManyField(blank=True, related_name='viewed_users', to='recipes.Recipe'),
        ),
    ]
