# Generated by Django 3.2.18 on 2023-06-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microwave', models.BooleanField(default=False)),
                ('stove', models.BooleanField(default=False)),
                ('oven', models.BooleanField(default=False)),
                ('air_fryer', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
