# Generated by Django 3.2.18 on 2023-06-09 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip',
            name='recipe',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
