# Generated by Django 3.2.18 on 2023-06-02 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_auto_20230602_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='bookmark',
        ),
        migrations.AlterModelTable(
            name='likerecipe',
            table='like_recipe',
        ),
        migrations.CreateModel(
            name='BookMarkRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookmark_recipe',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='bookmark_users',
            field=models.ManyToManyField(blank=True, related_name='bookmark_recipes', through='recipes.BookMarkRecipe', to=settings.AUTH_USER_MODEL),
        ),
    ]
